name: RF_py39
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - netcdf4
    - python=3.9
    - pip
    - pytorch=1.13.1
    - torchvision=0.14.1
    - torchaudio=0.13.1
    - pytorch-cuda=11.7
    - xarray
    - gcm_filters
    - pip:
        - matplotlib
        - wandb
